### ISSUE TITLE
Setup scheduled build

### ISSUE THREAD

**Issue by ronnie-llamado** [cenpy-devs/cenpy#129]
Would it be beneficial to setup a weekly or monthly build? With the amount of the time since the last build, it's a bit harder to pinpoint when and where some warnings and errors started to pop up.

**Comment by ljwolf** [comment]
I think I used to have a build enabled on nightli.es, but I think those builds stopped when the repository migrated to the cenpy-devs organisation. 

I just have not had time to take a look at reenabling it... I've meant to move to GitHub actions for this kind of thing rather than relying on third parties, but that's again a migration.

**Comment by ronnie-llamado** [comment]
I'll take a look at migrating to GitHub actions.

How regular do you think the builds should be? GitHub's monthly limit is 2000 minutes - so at ~10 minutes/build, daily is out of the question.

**Comment by ljwolf** [comment]
Weekly would be sufficient, I think... The API generally doesn't change *that* often, it's just my own (& other cenpy-devs contributors) limited time that results in lagged responses to the changes!
